extern const GeoLayout purp_geo[];
extern Lights1 purp_body1_f3d_lights;
extern Lights1 purp_vertexColors_001_f3d_lights;
extern u8 purp_piki2_color_s3tc_rgba16[];
extern u8 purp_vertexColors_flower_red_rgba16[];
extern Vtx purp_meshes_0_0_mesh_layer_1_vtx_0[261];
extern Gfx purp_meshes_0_0_mesh_layer_1_tri_0[];
extern Vtx purp_meshes_0_0_mesh_layer_1_vtx_1[204];
extern Gfx purp_meshes_0_0_mesh_layer_1_tri_1[];
extern Gfx mat_purp_body1_f3d[];
extern Gfx mat_purp_vertexColors_001_f3d[];
extern Gfx purp_meshes_0_0_mesh_layer_1[];
extern Gfx purp_material_revert_render_settings[];
