extern const GeoLayout ttm_area_1_geo[];
extern const GeoLayout ttm_area_1[];
extern const Collision ttm_area_1_collision[];
extern const MacroObject ttm_area_1_macro_objs[];
extern const GeoLayout ttm_area_2_geo[];
extern const GeoLayout ttm_area_2[];
extern const Collision ttm_area_2_collision[];
extern const MacroObject ttm_area_2_macro_objs[];
extern Lights1 ttm_dl_f3d_material_lights;
extern Lights1 ttm_dl_dashpad_lights;
extern Lights1 ttm_dl_f3d_material_001_lights;
extern u8 ttm_dl_Sand_ci8[];
extern u8 ttm_dl_Sand_ci8_pal_rgba16[];
extern u8 ttm_dl_dash_pannel_texture_rgba16[];
extern Vtx ttm_dl_Cube_mesh_layer_1_vtx_0[83];
extern Gfx ttm_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx ttm_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx ttm_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx ttm_dl_Cube_001_mesh_layer_1_vtx_0[24];
extern Gfx ttm_dl_Cube_001_mesh_layer_1_tri_0[];
extern Gfx mat_ttm_dl_f3d_material[];
extern Gfx mat_revert_ttm_dl_f3d_material[];
extern Gfx mat_ttm_dl_dashpad[];
extern Gfx mat_ttm_dl_f3d_material_001[];
extern Gfx ttm_dl_Cube_mesh_layer_1[];
extern Gfx ttm_dl_Plane_mesh_layer_1[];
extern Gfx ttm_dl_Cube_001_mesh_layer_1[];
extern Gfx ttm_dl_material_revert_render_settings[];
