extern const GeoLayout ttm_area_1_geo[];
extern const GeoLayout ttm_area_1[];
extern const Collision ttm_area_1_collision[];
extern const MacroObject ttm_area_1_macro_objs[];
extern const GeoLayout ttm_area_2_geo[];
extern const GeoLayout ttm_area_2[];
extern const Collision ttm_area_2_collision[];
extern const MacroObject ttm_area_2_macro_objs[];
extern Lights1 ttm_dl_f3d_material_v4_001_lights;
extern Lights1 ttm_dl_f3d_material_002_v4_lights;
extern Lights1 ttm_dl_wall_v4_002_lights;
extern Lights1 ttm_dl_f3d_material_001_v4_lights;
extern Lights1 ttm_dl_dashpad_v4_lights;
extern u8 ttm_dl_Sand_ci8[];
extern u8 ttm_dl_Sand_ci8_pal_rgba16[];
extern u8 ttm_dl_wall_ci8[];
extern u8 ttm_dl_wall_ci8_pal_rgba16[];
extern u8 ttm_dl_dash_pannel_texture_rgba16[];
extern Vtx ttm_dl_Cube_mesh_layer_1_vtx_0[47];
extern Gfx ttm_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx ttm_dl_Cube_mesh_layer_1_vtx_1[4];
extern Gfx ttm_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx ttm_dl_Cube_mesh_layer_1_vtx_2[46];
extern Gfx ttm_dl_Cube_mesh_layer_1_tri_2[];
extern Vtx ttm_dl_Cube_002_mesh_layer_1_vtx_0[38];
extern Gfx ttm_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx ttm_dl_Cube_002_mesh_layer_1_vtx_1[100];
extern Gfx ttm_dl_Cube_002_mesh_layer_1_tri_1[];
extern Vtx ttm_dl_Cube_002_mesh_layer_1_vtx_2[10];
extern Gfx ttm_dl_Cube_002_mesh_layer_1_tri_2[];
extern Vtx ttm_dl_Cube_001_mesh_layer_1_vtx_0[24];
extern Gfx ttm_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx ttm_dl_Plane_001_mesh_layer_1_vtx_0[4];
extern Gfx ttm_dl_Plane_001_mesh_layer_1_tri_0[];
extern Gfx mat_ttm_dl_f3d_material_v4_001[];
extern Gfx mat_revert_ttm_dl_f3d_material_v4_001[];
extern Gfx mat_ttm_dl_f3d_material_002_v4[];
extern Gfx mat_ttm_dl_wall_v4_002[];
extern Gfx mat_revert_ttm_dl_wall_v4_002[];
extern Gfx mat_ttm_dl_f3d_material_001_v4[];
extern Gfx mat_ttm_dl_dashpad_v4[];
extern Gfx ttm_dl_Cube_mesh_layer_1[];
extern Gfx ttm_dl_Cube_002_mesh_layer_1[];
extern Gfx ttm_dl_Cube_001_mesh_layer_1[];
extern Gfx ttm_dl_Plane_001_mesh_layer_1[];
extern Gfx ttm_dl_material_revert_render_settings[];
