extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_Material_f3d_lights;
extern Lights1 bob_dl_f3d_material_004_lights;
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx bob_dl_DeathPlane_mesh_layer_5_vtx_0[4];
extern Gfx bob_dl_DeathPlane_mesh_layer_5_tri_0[];
extern Gfx mat_bob_dl_Material_f3d[];
extern Gfx mat_bob_dl_f3d_material_004[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
extern Gfx bob_dl_Cube_001_mesh_layer_1[];
extern Gfx bob_dl_DeathPlane_mesh_layer_5[];
extern Gfx bob_dl_material_revert_render_settings[];
