extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
extern Lights1 bob_dl_Material_f3d_001_lights;
extern Lights1 bob_dl_right_lights;
extern Lights1 bob_dl_f3dlite_material_001_lights;
extern Lights1 bob_dl_f3dlite_material_002_lights;
extern Lights1 bob_dl_f3dlite_material_003_lights;
extern Lights1 bob_dl_f3d_material_004_lights;
extern Lights1 bob_dl_Material_f3d_002_lights;
extern Lights1 bob_dl_f3d_material_001_lights;
extern u8 bob_dl_dash_pannel_texture_rgba16[];
extern u8 bob_dl_dash_pannel_texture_rgba16_copy[];
extern u8 bob_dl_dash_pannel_texture_rgba16_copy_copy[];
extern u8 bob_dl_dash_pannel_texture_rgba16_copy_copy_copy[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_002_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_003_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_003_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_004_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_004_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_005_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_005_mesh_layer_1_tri_0[];
extern Vtx bob_dl_DeathPlane_mesh_layer_5_vtx_0[4];
extern Gfx bob_dl_DeathPlane_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Cube_006_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_006_mesh_layer_1_tri_0[];
extern Vtx bob_dl_DeathPlane_001_mesh_layer_5_vtx_0[4];
extern Gfx bob_dl_DeathPlane_001_mesh_layer_5_tri_0[];
extern Gfx mat_bob_dl_Material_f3d_001[];
extern Gfx mat_bob_dl_right[];
extern Gfx mat_bob_dl_f3dlite_material_001[];
extern Gfx mat_bob_dl_f3dlite_material_002[];
extern Gfx mat_bob_dl_f3dlite_material_003[];
extern Gfx mat_bob_dl_f3d_material_004[];
extern Gfx mat_bob_dl_Material_f3d_002[];
extern Gfx mat_bob_dl_f3d_material_001[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
extern Gfx bob_dl_Cube_001_mesh_layer_1[];
extern Gfx bob_dl_Cube_002_mesh_layer_1[];
extern Gfx bob_dl_Cube_003_mesh_layer_1[];
extern Gfx bob_dl_Cube_004_mesh_layer_1[];
extern Gfx bob_dl_Cube_005_mesh_layer_1[];
extern Gfx bob_dl_DeathPlane_mesh_layer_5[];
extern Gfx bob_dl_Cube_006_mesh_layer_1[];
extern Gfx bob_dl_DeathPlane_001_mesh_layer_5[];
extern Gfx bob_dl_material_revert_render_settings[];
