extern const GeoLayout ggoblin_geo[];
extern Lights1 ggoblin_GREENGOBLIN_f3d_lights;
extern u8 ggoblin_GREENGOBLIN_ci8[];
extern u8 ggoblin_GREENGOBLIN_ci8_pal_rgba16[];
extern Vtx ggoblin_rdmobj00_mesh_layer_1_vtx_0[1203];
extern Gfx ggoblin_rdmobj00_mesh_layer_1_tri_0[];
extern Gfx mat_ggoblin_GREENGOBLIN_f3d[];
extern Gfx mat_revert_ggoblin_GREENGOBLIN_f3d[];
extern Gfx ggoblin_rdmobj00_mesh_layer_1[];
extern Gfx ggoblin_material_revert_render_settings[];
